@extends('layouts.app')
@section('title', __('Users'))
@section('page-title', __('Users'))
@section('page-subtitle', __('Manage application accounts and role membership'))
@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"><div class="text-secondary">{{ trans_choice('ui.counts.users', $users->total(), ['count' => $users->total()]) }}</div>@can('create', App\Models\User::class)<a href="{{ route('users.create') }}" class="btn btn-primary"><i class="bi bi-person-plus me-1"></i> {{ __('New user') }}</a>@endcan</div>
    <div class="card fm-card mb-4"><div class="card-body"><form method="GET" action="{{ route('users.index') }}"><div class="row g-3"><div class="col-12 col-lg-8"><label for="search" class="form-label fw-semibold">{{ __('Search') }}</label><input id="search" name="search" class="form-control" value="{{ $filters['search'] }}" placeholder="{{ __('Name or email...') }}"></div><div class="col-12 col-lg-4"><label for="role_id" class="form-label fw-semibold">{{ __('Role') }}</label><select id="role_id" name="role_id" class="form-select"><option value="">{{ __('All roles') }}</option>@foreach ($roles as $role)<option value="{{ $role->id }}" @selected((string) $filters['role_id'] === (string) $role->id)>{{ __($role->name) }}</option>@endforeach</select></div></div><div class="d-flex justify-content-end gap-2 mt-3"><a href="{{ route('users.index') }}" class="btn btn-outline-secondary">{{ __('Reset') }}</a><button class="btn btn-primary">{{ __('Apply filters') }}</button></div></form></div></div>
    <div class="card fm-card"><div class="table-responsive"><table class="table align-middle mb-0 fm-table"><thead><tr><th>{{ __('User') }}</th><th>{{ __('Roles') }}</th><th>{{ __('Created') }}</th><th class="text-end">{{ __('Actions') }}</th></tr></thead><tbody>
        @forelse ($users as $user)
            <tr><td><div class="d-flex align-items-center gap-3"><div class="fm-small-avatar">{{ strtoupper(substr($user->name, 0, 1)) }}</div><div><a href="{{ route('users.show', $user) }}" class="fw-semibold text-dark">{{ $user->name }}</a><div class="small text-secondary">{{ $user->email }}</div></div></div></td><td>@forelse ($user->roles as $role)<span class="badge text-bg-primary me-1">{{ __($role->name) }}</span>@empty<span class="text-secondary">{{ __('No role') }}</span>@endforelse</td><td>{{ $user->created_at->format('d/m/Y') }}</td><td class="text-end"><div class="btn-group"><a href="{{ route('users.show', $user) }}" class="btn btn-sm btn-outline-secondary" title="{{ __('View') }}"><i class="bi bi-eye"></i></a>@can('update', $user)<a href="{{ route('users.edit', $user) }}" class="btn btn-sm btn-outline-secondary" title="{{ __('Edit') }}"><i class="bi bi-pencil"></i></a>@endcan @can('delete', $user)<form method="POST" action="{{ route('users.destroy', $user) }}" onsubmit="return confirm(@js(__('Delete this user?')));">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger rounded-start-0" title="{{ __('Delete') }}"><i class="bi bi-trash"></i></button></form>@endcan</div></td></tr>
        @empty<tr><td colspan="4" class="text-center py-5"><i class="bi bi-people fs-1 text-secondary"></i><div class="fw-semibold mt-3">{{ __('No users found') }}</div><div class="text-secondary">{{ __('Create an account or change the active filters.') }}</div></td></tr>@endforelse
    </tbody></table></div>@if ($users->hasPages())<div class="card-footer bg-white p-3">{{ $users->links() }}</div>@endif</div>
@endsection
