<?php $__env->startSection('title', __('Tickets')); ?>
<?php $__env->startSection('page-title', __('Tickets')); ?>
<?php $__env->startSection('page-subtitle', __('Manage support requests, ownership and resolution')); ?>
<?php $__env->startSection('content'); ?>
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"><div class="text-secondary"><?php echo e(trans_choice('ui.counts.tickets', $tickets->total(), ['count' => $tickets->total()])); ?></div><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('create', App\Models\Ticket::class)): ?><a href="<?php echo e(route('tickets.create')); ?>" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i> <?php echo e(__('New ticket')); ?></a><?php endif; ?></div>
    <div class="card fm-card mb-4"><div class="card-body"><form method="GET" action="<?php echo e(route('tickets.index')); ?>"><div class="row g-3">
        <div class="col-12 col-lg-4"><label for="search" class="form-label fw-semibold"><?php echo e(__('Search')); ?></label><input id="search" name="search" class="form-control" value="<?php echo e($filters['search']); ?>" placeholder="<?php echo e(__('Reference, subject, company, contact...')); ?>"></div>
        <div class="col-12 col-md-6 col-lg-2"><label for="company_id" class="form-label fw-semibold"><?php echo e(__('Company')); ?></label><select id="company_id" name="company_id" class="form-select"><option value=""><?php echo e(__('All companies')); ?></option><?php $__currentLoopData = $companies; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $company): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($company->id); ?>" <?php if((string) $filters['company_id'] === (string) $company->id): echo 'selected'; endif; ?>><?php echo e($company->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="status" class="form-label fw-semibold"><?php echo e(__('Status')); ?></label><select id="status" name="status" class="form-select"><option value=""><?php echo e(__('All statuses')); ?></option><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($status->value); ?>" <?php if($filters['status'] === $status->value): echo 'selected'; endif; ?>><?php echo e($status->label()); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="priority" class="form-label fw-semibold"><?php echo e(__('Priority')); ?></label><select id="priority" name="priority" class="form-select"><option value=""><?php echo e(__('All priorities')); ?></option><?php $__currentLoopData = $priorities; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $priority): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($priority->value); ?>" <?php if($filters['priority'] === $priority->value): echo 'selected'; endif; ?>><?php echo e($priority->label()); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-12 col-md-6 col-lg-2"><label for="assigned_to" class="form-label fw-semibold"><?php echo e(__('Assigned to')); ?></label><select id="assigned_to" name="assigned_to" class="form-select"><option value=""><?php echo e(__('All users')); ?></option><?php $__currentLoopData = $users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($user->id); ?>" <?php if((string) $filters['assigned_to'] === (string) $user->id): echo 'selected'; endif; ?>><?php echo e($user->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-12 col-md-6 col-lg-3"><label for="sort" class="form-label fw-semibold"><?php echo e(__('Sort by')); ?></label><select id="sort" name="sort" class="form-select"><?php $__currentLoopData = ['created_at' => 'Created', 'reference' => 'Reference', 'subject' => 'Subject', 'status' => 'Status', 'priority' => 'Priority', 'resolved_at' => 'Resolved']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if($filters['sort'] === $value): echo 'selected'; endif; ?>><?php echo e(__($label)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="direction" class="form-label fw-semibold"><?php echo e(__('Order')); ?></label><select id="direction" name="direction" class="form-select"><option value="desc" <?php if($filters['direction'] === 'desc'): echo 'selected'; endif; ?>><?php echo e(__('Descending')); ?></option><option value="asc" <?php if($filters['direction'] === 'asc'): echo 'selected'; endif; ?>><?php echo e(__('Ascending')); ?></option></select></div>
    </div><div class="d-flex justify-content-end gap-2 mt-3"><a href="<?php echo e(route('tickets.index')); ?>" class="btn btn-outline-secondary"><?php echo e(__('Reset')); ?></a><button class="btn btn-primary"><?php echo e(__('Apply filters')); ?></button></div></form></div></div>

    <div class="card fm-card"><div class="table-responsive"><table class="table align-middle mb-0 fm-table"><thead><tr><th><?php echo e(__('Ticket')); ?></th><th><?php echo e(__('Company / Contact')); ?></th><th><?php echo e(__('Status')); ?></th><th><?php echo e(__('Priority')); ?></th><th><?php echo e(__('Assigned to')); ?></th><th><?php echo e(__('SLA')); ?></th><th><?php echo e(__('Created')); ?></th><th class="text-end"><?php echo e(__('Actions')); ?></th></tr></thead><tbody>
        <?php $__empty_1 = true; $__currentLoopData = $tickets; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $ticket): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <?php
                $statusClass = match ($ticket->status->value) {'open' => 'text-bg-danger', 'in_progress' => 'text-bg-primary', 'waiting' => 'text-bg-warning', 'resolved' => 'text-bg-success', default => 'text-bg-secondary'};
                $priorityClass = match ($ticket->priority->value) {'urgent' => 'text-bg-danger', 'high' => 'text-bg-warning', 'low' => 'text-bg-light border text-secondary', default => 'text-bg-primary'};
            ?>
            <tr><td><a class="fw-semibold text-dark" href="<?php echo e(route('tickets.show', $ticket)); ?>"><?php echo e($ticket->subject); ?></a><div class="small text-secondary"><?php echo e($ticket->reference); ?> · <?php echo e($ticket->category->label()); ?></div></td><td><?php if($ticket->company): ?><a href="<?php echo e(route('companies.show', $ticket->company)); ?>"><?php echo e($ticket->company->name); ?></a><?php else: ?>—<?php endif; ?> <?php if($ticket->contact): ?><div class="small text-secondary"><a class="text-secondary" href="<?php echo e(route('contacts.show', $ticket->contact)); ?>"><?php echo e($ticket->contact->full_name); ?></a></div><?php endif; ?></td><td><span class="badge <?php echo e($statusClass); ?>"><?php echo e($ticket->status->label()); ?></span></td><td><span class="badge <?php echo e($priorityClass); ?>"><?php echo e($ticket->priority->label()); ?></span></td><td><?php echo e($ticket->assignee?->name ?: '—'); ?></td><td><?php if($ticket->sla_due_at): ?><span class="badge <?php echo e($ticket->isSlaBreached() ? 'text-bg-danger' : 'text-bg-light border text-secondary'); ?>"><?php echo e($ticket->isSlaBreached() ? __('Breached') : $ticket->sla_due_at->format('d/m H:i')); ?></span><?php else: ?>—<?php endif; ?></td><td><?php echo e($ticket->created_at->format('d/m/Y')); ?></td><td class="text-end"><div class="btn-group"><a href="<?php echo e(route('tickets.show', $ticket)); ?>" class="btn btn-sm btn-outline-secondary" title="<?php echo e(__('View')); ?>"><i class="bi bi-eye"></i></a><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('update', $ticket)): ?><a href="<?php echo e(route('tickets.edit', $ticket)); ?>" class="btn btn-sm btn-outline-secondary" title="<?php echo e(__('Edit')); ?>"><i class="bi bi-pencil"></i></a><?php endif; ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('delete', $ticket)): ?><form method="POST" action="<?php echo e(route('tickets.destroy', $ticket)); ?>" onsubmit="return confirm(<?php echo \Illuminate\Support\Js::from(__('Delete this ticket?'))->toHtml() ?>);"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger rounded-start-0" title="<?php echo e(__('Delete')); ?>"><i class="bi bi-trash"></i></button></form><?php endif; ?></div></td></tr>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="8" class="text-center py-5"><i class="bi bi-ticket-perforated fs-1 text-secondary"></i><div class="fw-semibold mt-3"><?php echo e(__('No tickets found')); ?></div><div class="text-secondary"><?php echo e(__('Open a ticket or change the active filters.')); ?></div></td></tr><?php endif; ?>
    </tbody></table></div><?php if($tickets->hasPages()): ?><div class="card-footer bg-white p-3"><?php echo e($tickets->links()); ?></div><?php endif; ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Projects\flowmanager\resources\views/tickets/index.blade.php ENDPATH**/ ?>