<?php $__env->startSection('title', __('Assets')); ?>
<?php $__env->startSection('page-title', __('Assets')); ?>
<?php $__env->startSection('page-subtitle', __('Inventory, ownership, assignment and lifecycle tracking')); ?>
<?php $__env->startSection('content'); ?>
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"><div class="text-secondary"><?php echo e(trans_choice('ui.counts.assets', $assets->total(), ['count' => $assets->total()])); ?></div><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('create', App\Models\Asset::class)): ?><a href="<?php echo e(route('assets.create')); ?>" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i> <?php echo e(__('New asset')); ?></a><?php endif; ?></div>
    <div class="card fm-card mb-4"><div class="card-body"><form method="GET" action="<?php echo e(route('assets.index')); ?>"><div class="row g-3">
        <div class="col-12 col-lg-4"><label for="search" class="form-label fw-semibold"><?php echo e(__('Search')); ?></label><input id="search" name="search" class="form-control" value="<?php echo e($filters['search']); ?>" placeholder="<?php echo e(__('Tag, serial, model, company...')); ?>"></div>
        <div class="col-12 col-md-6 col-lg-2"><label for="company_id" class="form-label fw-semibold"><?php echo e(__('Company')); ?></label><select id="company_id" name="company_id" class="form-select"><option value=""><?php echo e(__('All companies')); ?></option><?php $__currentLoopData = $companies; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $company): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($company->id); ?>" <?php if((string) $filters['company_id'] === (string) $company->id): echo 'selected'; endif; ?>><?php echo e($company->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="status" class="form-label fw-semibold"><?php echo e(__('Status')); ?></label><select id="status" name="status" class="form-select"><option value=""><?php echo e(__('All statuses')); ?></option><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($status->value); ?>" <?php if($filters['status'] === $status->value): echo 'selected'; endif; ?>><?php echo e($status->label()); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="category" class="form-label fw-semibold"><?php echo e(__('Category')); ?></label><select id="category" name="category" class="form-select"><option value=""><?php echo e(__('All categories')); ?></option><?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($category); ?>" <?php if($filters['category'] === $category): echo 'selected'; endif; ?>><?php echo e($category); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-12 col-md-6 col-lg-2"><label for="assigned_to" class="form-label fw-semibold"><?php echo e(__('Assigned to')); ?></label><select id="assigned_to" name="assigned_to" class="form-select"><option value=""><?php echo e(__('All users')); ?></option><?php $__currentLoopData = $users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($user->id); ?>" <?php if((string) $filters['assigned_to'] === (string) $user->id): echo 'selected'; endif; ?>><?php echo e($user->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-12 col-md-6 col-lg-3"><label for="sort" class="form-label fw-semibold"><?php echo e(__('Sort by')); ?></label><select id="sort" name="sort" class="form-select"><?php $__currentLoopData = ['asset_tag' => 'Asset tag', 'name' => 'Name', 'category' => 'Category', 'status' => 'Status', 'purchase_date' => 'Purchase date', 'created_at' => 'Created']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if($filters['sort'] === $value): echo 'selected'; endif; ?>><?php echo e(__($label)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="direction" class="form-label fw-semibold"><?php echo e(__('Order')); ?></label><select id="direction" name="direction" class="form-select"><option value="asc" <?php if($filters['direction'] === 'asc'): echo 'selected'; endif; ?>><?php echo e(__('Ascending')); ?></option><option value="desc" <?php if($filters['direction'] === 'desc'): echo 'selected'; endif; ?>><?php echo e(__('Descending')); ?></option></select></div>
    </div><div class="d-flex justify-content-end gap-2 mt-3"><a href="<?php echo e(route('assets.index')); ?>" class="btn btn-outline-secondary"><?php echo e(__('Reset')); ?></a><button class="btn btn-primary"><?php echo e(__('Apply filters')); ?></button></div></form></div></div>

    <div class="card fm-card"><div class="table-responsive"><table class="table align-middle mb-0 fm-table"><thead><tr><th><?php echo e(__('Asset')); ?></th><th><?php echo e(__('Category')); ?></th><th><?php echo e(__('Company')); ?></th><th><?php echo e(__('Assigned to')); ?></th><th><?php echo e(__('Status')); ?></th><th><?php echo e(__('Serial')); ?></th><th class="text-end"><?php echo e(__('Actions')); ?></th></tr></thead><tbody>
        <?php $__empty_1 = true; $__currentLoopData = $assets; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $asset): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <?php $statusClass = match ($asset->status->value) {'available' => 'text-bg-success', 'assigned' => 'text-bg-primary', 'maintenance' => 'text-bg-warning', 'lost' => 'text-bg-danger', default => 'text-bg-secondary'}; ?>
            <tr><td><a class="fw-semibold text-dark" href="<?php echo e(route('assets.show', $asset)); ?>"><?php echo e($asset->name); ?></a><div class="small text-secondary"><?php echo e($asset->asset_tag); ?><?php echo e($asset->brand ? ' · '.$asset->brand : ''); ?></div></td><td><?php echo e($asset->category ?: '—'); ?></td><td><?php echo e($asset->company?->name ?: __('Internal')); ?></td><td><?php echo e($asset->assignee?->name ?: '—'); ?></td><td><span class="badge <?php echo e($statusClass); ?>"><?php echo e($asset->status->label()); ?></span></td><td><?php echo e($asset->serial_number ?: '—'); ?></td><td class="text-end"><div class="btn-group"><a href="<?php echo e(route('assets.show', $asset)); ?>" class="btn btn-sm btn-outline-secondary" title="<?php echo e(__('View')); ?>"><i class="bi bi-eye"></i></a><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('assign', $asset)): ?><a href="<?php echo e(route('assets.assignment.edit', $asset)); ?>" class="btn btn-sm btn-outline-secondary" title="<?php echo e(__('Assign')); ?>"><i class="bi bi-person-check"></i></a><?php endif; ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('update', $asset)): ?><a href="<?php echo e(route('assets.edit', $asset)); ?>" class="btn btn-sm btn-outline-secondary" title="<?php echo e(__('Edit')); ?>"><i class="bi bi-pencil"></i></a><?php endif; ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('delete', $asset)): ?><form method="POST" action="<?php echo e(route('assets.destroy', $asset)); ?>" onsubmit="return confirm(<?php echo \Illuminate\Support\Js::from(__('Delete this asset?'))->toHtml() ?>);"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger rounded-start-0" title="<?php echo e(__('Delete')); ?>"><i class="bi bi-trash"></i></button></form><?php endif; ?></div></td></tr>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center py-5"><i class="bi bi-laptop fs-1 text-secondary"></i><div class="fw-semibold mt-3"><?php echo e(__('No assets found')); ?></div><div class="text-secondary"><?php echo e(__('Register an asset or change the active filters.')); ?></div></td></tr><?php endif; ?>
    </tbody></table></div><?php if($assets->hasPages()): ?><div class="card-footer bg-white p-3"><?php echo e($assets->links()); ?></div><?php endif; ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Projects\flowmanager\resources\views/assets/index.blade.php ENDPATH**/ ?>