<?php $__env->startSection('title', __('Users')); ?>
<?php $__env->startSection('page-title', __('Users')); ?>
<?php $__env->startSection('page-subtitle', __('Manage application accounts and role membership')); ?>
<?php $__env->startSection('content'); ?>
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"><div class="text-secondary"><?php echo e(trans_choice('ui.counts.users', $users->total(), ['count' => $users->total()])); ?></div><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('create', App\Models\User::class)): ?><a href="<?php echo e(route('users.create')); ?>" class="btn btn-primary"><i class="bi bi-person-plus me-1"></i> <?php echo e(__('New user')); ?></a><?php endif; ?></div>
    <div class="card fm-card mb-4"><div class="card-body"><form method="GET" action="<?php echo e(route('users.index')); ?>"><div class="row g-3"><div class="col-12 col-lg-8"><label for="search" class="form-label fw-semibold"><?php echo e(__('Search')); ?></label><input id="search" name="search" class="form-control" value="<?php echo e($filters['search']); ?>" placeholder="<?php echo e(__('Name or email...')); ?>"></div><div class="col-12 col-lg-4"><label for="role_id" class="form-label fw-semibold"><?php echo e(__('Role')); ?></label><select id="role_id" name="role_id" class="form-select"><option value=""><?php echo e(__('All roles')); ?></option><?php $__currentLoopData = $roles; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $role): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($role->id); ?>" <?php if((string) $filters['role_id'] === (string) $role->id): echo 'selected'; endif; ?>><?php echo e(__($role->name)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div></div><div class="d-flex justify-content-end gap-2 mt-3"><a href="<?php echo e(route('users.index')); ?>" class="btn btn-outline-secondary"><?php echo e(__('Reset')); ?></a><button class="btn btn-primary"><?php echo e(__('Apply filters')); ?></button></div></form></div></div>
    <div class="card fm-card"><div class="table-responsive"><table class="table align-middle mb-0 fm-table"><thead><tr><th><?php echo e(__('User')); ?></th><th><?php echo e(__('Roles')); ?></th><th><?php echo e(__('Created')); ?></th><th class="text-end"><?php echo e(__('Actions')); ?></th></tr></thead><tbody>
        <?php $__empty_1 = true; $__currentLoopData = $users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <tr><td><div class="d-flex align-items-center gap-3"><div class="fm-small-avatar"><?php echo e(strtoupper(substr($user->name, 0, 1))); ?></div><div><a href="<?php echo e(route('users.show', $user)); ?>" class="fw-semibold text-dark"><?php echo e($user->name); ?></a><div class="small text-secondary"><?php echo e($user->email); ?></div></div></div></td><td><?php $__empty_2 = true; $__currentLoopData = $user->roles; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $role): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_2 = false; ?><span class="badge text-bg-primary me-1"><?php echo e(__($role->name)); ?></span><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_2): ?><span class="text-secondary"><?php echo e(__('No role')); ?></span><?php endif; ?></td><td><?php echo e($user->created_at->format('d/m/Y')); ?></td><td class="text-end"><div class="btn-group"><a href="<?php echo e(route('users.show', $user)); ?>" class="btn btn-sm btn-outline-secondary" title="<?php echo e(__('View')); ?>"><i class="bi bi-eye"></i></a><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('update', $user)): ?><a href="<?php echo e(route('users.edit', $user)); ?>" class="btn btn-sm btn-outline-secondary" title="<?php echo e(__('Edit')); ?>"><i class="bi bi-pencil"></i></a><?php endif; ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('delete', $user)): ?><form method="POST" action="<?php echo e(route('users.destroy', $user)); ?>" onsubmit="return confirm(<?php echo \Illuminate\Support\Js::from(__('Delete this user?'))->toHtml() ?>);"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger rounded-start-0" title="<?php echo e(__('Delete')); ?>"><i class="bi bi-trash"></i></button></form><?php endif; ?></div></td></tr>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="4" class="text-center py-5"><i class="bi bi-people fs-1 text-secondary"></i><div class="fw-semibold mt-3"><?php echo e(__('No users found')); ?></div><div class="text-secondary"><?php echo e(__('Create an account or change the active filters.')); ?></div></td></tr><?php endif; ?>
    </tbody></table></div><?php if($users->hasPages()): ?><div class="card-footer bg-white p-3"><?php echo e($users->links()); ?></div><?php endif; ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Projects\flowmanager\resources\views/users/index.blade.php ENDPATH**/ ?>