<?php $__env->startSection('title', __('Tasks')); ?>
<?php $__env->startSection('page-title', __('Tasks')); ?>
<?php $__env->startSection('page-subtitle', __('Track project work, ownership, priority and deadlines')); ?>
<?php $__env->startSection('content'); ?>
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"><div class="text-secondary"><?php echo e(trans_choice('ui.counts.tasks', $tasks->total(), ['count' => $tasks->total()])); ?></div><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('create', App\Models\Task::class)): ?><a href="<?php echo e(route('tasks.create')); ?>" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i> <?php echo e(__('New task')); ?></a><?php endif; ?></div>
    <div class="card fm-card mb-4"><div class="card-body"><form method="GET" action="<?php echo e(route('tasks.index')); ?>"><div class="row g-3">
        <div class="col-12 col-lg-4"><label for="search" class="form-label fw-semibold"><?php echo e(__('Search')); ?></label><input id="search" name="search" class="form-control" value="<?php echo e($filters['search']); ?>" placeholder="<?php echo e(__('Task or project...')); ?>"></div>
        <div class="col-12 col-md-6 col-lg-2"><label for="project_id" class="form-label fw-semibold"><?php echo e(__('Project')); ?></label><select id="project_id" name="project_id" class="form-select"><option value=""><?php echo e(__('All projects')); ?></option><?php $__currentLoopData = $projects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $project): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($project->id); ?>" <?php if((string) $filters['project_id'] === (string) $project->id): echo 'selected'; endif; ?>><?php echo e($project->code); ?> — <?php echo e($project->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="status" class="form-label fw-semibold"><?php echo e(__('Status')); ?></label><select id="status" name="status" class="form-select"><option value=""><?php echo e(__('All statuses')); ?></option><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($status->value); ?>" <?php if($filters['status'] === $status->value): echo 'selected'; endif; ?>><?php echo e($status->label()); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="priority" class="form-label fw-semibold"><?php echo e(__('Priority')); ?></label><select id="priority" name="priority" class="form-select"><option value=""><?php echo e(__('All priorities')); ?></option><?php $__currentLoopData = $priorities; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $priority): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($priority->value); ?>" <?php if($filters['priority'] === $priority->value): echo 'selected'; endif; ?>><?php echo e($priority->label()); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-12 col-md-6 col-lg-2"><label for="assigned_to" class="form-label fw-semibold"><?php echo e(__('Assignee')); ?></label><select id="assigned_to" name="assigned_to" class="form-select"><option value=""><?php echo e(__('All users')); ?></option><?php $__currentLoopData = $users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($user->id); ?>" <?php if((string) $filters['assigned_to'] === (string) $user->id): echo 'selected'; endif; ?>><?php echo e($user->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-12 col-md-6 col-lg-3"><label for="sort" class="form-label fw-semibold"><?php echo e(__('Sort by')); ?></label><select id="sort" name="sort" class="form-select"><?php $__currentLoopData = ['due_date' => 'Due date', 'title' => 'Title', 'status' => 'Status', 'priority' => 'Priority', 'created_at' => 'Created']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if($filters['sort'] === $value): echo 'selected'; endif; ?>><?php echo e(__($label)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="direction" class="form-label fw-semibold"><?php echo e(__('Order')); ?></label><select id="direction" name="direction" class="form-select"><option value="asc" <?php if($filters['direction'] === 'asc'): echo 'selected'; endif; ?>><?php echo e(__('Ascending')); ?></option><option value="desc" <?php if($filters['direction'] === 'desc'): echo 'selected'; endif; ?>><?php echo e(__('Descending')); ?></option></select></div>
    </div><div class="d-flex justify-content-end gap-2 mt-3"><a href="<?php echo e(route('tasks.index')); ?>" class="btn btn-outline-secondary"><?php echo e(__('Reset')); ?></a><button class="btn btn-primary" type="submit"><?php echo e(__('Apply filters')); ?></button></div></form></div></div>

    <div class="card fm-card"><div class="table-responsive"><table class="table align-middle mb-0 fm-table"><thead><tr><th><?php echo e(__('Task')); ?></th><th><?php echo e(__('Project')); ?></th><th><?php echo e(__('Status')); ?></th><th><?php echo e(__('Priority')); ?></th><th><?php echo e(__('Assignee')); ?></th><th><?php echo e(__('Due date')); ?></th><th class="text-end"><?php echo e(__('Actions')); ?></th></tr></thead><tbody>
        <?php $__empty_1 = true; $__currentLoopData = $tasks; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $task): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <?php
                $statusClass = match ($task->status->value) {'completed' => 'text-bg-success', 'in_progress' => 'text-bg-primary', 'blocked' => 'text-bg-danger', 'cancelled' => 'text-bg-secondary', default => 'text-bg-light border text-secondary'};
                $priorityClass = match ($task->priority->value) {'urgent' => 'text-bg-danger', 'high' => 'text-bg-warning', 'low' => 'text-bg-light border text-secondary', default => 'text-bg-primary'};
            ?>
            <tr><td><a class="fw-semibold text-dark" href="<?php echo e(route('tasks.show', $task)); ?>"><?php echo e($task->title); ?></a></td><td><a href="<?php echo e(route('projects.show', $task->project)); ?>"><?php echo e($task->project->code); ?></a><div class="small text-secondary"><?php echo e($task->project->name); ?></div></td><td><span class="badge <?php echo e($statusClass); ?>"><?php echo e($task->status->label()); ?></span></td><td><span class="badge <?php echo e($priorityClass); ?>"><?php echo e($task->priority->label()); ?></span></td><td><?php echo e($task->assignee?->name ?: '—'); ?></td><td><?php echo e($task->due_date?->format('d/m/Y') ?: '—'); ?></td><td class="text-end"><div class="btn-group"><a href="<?php echo e(route('tasks.show', $task)); ?>" class="btn btn-sm btn-outline-secondary" title="<?php echo e(__('View')); ?>"><i class="bi bi-eye"></i></a><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('update', $task)): ?><a href="<?php echo e(route('tasks.edit', $task)); ?>" class="btn btn-sm btn-outline-secondary" title="<?php echo e(__('Edit')); ?>"><i class="bi bi-pencil"></i></a><?php endif; ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('delete', $task)): ?><form method="POST" action="<?php echo e(route('tasks.destroy', $task)); ?>" onsubmit="return confirm(<?php echo \Illuminate\Support\Js::from(__('Delete this task?'))->toHtml() ?>);"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger rounded-start-0" title="<?php echo e(__('Delete')); ?>"><i class="bi bi-trash"></i></button></form><?php endif; ?></div></td></tr>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center py-5"><i class="bi bi-check2-square fs-1 text-secondary"></i><div class="fw-semibold mt-3"><?php echo e(__('No tasks found')); ?></div><div class="text-secondary"><?php echo e(__('Create a task or change the active filters.')); ?></div></td></tr><?php endif; ?>
    </tbody></table></div><?php if($tasks->hasPages()): ?><div class="card-footer bg-white p-3"><?php echo e($tasks->links()); ?></div><?php endif; ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Projects\flowmanager\resources\views/tasks/index.blade.php ENDPATH**/ ?>