<?php $__env->startSection('title', __('Roles')); ?>
<?php $__env->startSection('page-title', __('Roles')); ?>
<?php $__env->startSection('page-subtitle', __('Control permission sets and application access profiles')); ?>
<?php $__env->startSection('content'); ?>
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"><div class="text-secondary"><?php echo e(trans_choice('ui.counts.roles', $roles->total(), ['count' => $roles->total()])); ?></div><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('create', App\Models\Role::class)): ?><a href="<?php echo e(route('roles.create')); ?>" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i> <?php echo e(__('New role')); ?></a><?php endif; ?></div>
    <div class="card fm-card mb-4"><div class="card-body"><form method="GET" action="<?php echo e(route('roles.index')); ?>"><div class="row g-3 align-items-end"><div class="col-12 col-lg-10"><label for="search" class="form-label fw-semibold"><?php echo e(__('Search')); ?></label><input id="search" name="search" class="form-control" value="<?php echo e($search); ?>" placeholder="<?php echo e(__('Name, slug or description...')); ?>"></div><div class="col-12 col-lg-2"><div class="d-flex gap-2"><a href="<?php echo e(route('roles.index')); ?>" class="btn btn-outline-secondary flex-fill"><?php echo e(__('Reset')); ?></a><button class="btn btn-primary flex-fill"><?php echo e(__('Search')); ?></button></div></div></div></form></div></div>
    <div class="card fm-card"><div class="table-responsive"><table class="table align-middle mb-0 fm-table"><thead><tr><th><?php echo e(__('Role')); ?></th><th><?php echo e(__('Description')); ?></th><th><?php echo e(__('Users')); ?></th><th><?php echo e(__('Permissions')); ?></th><th><?php echo e(__('Type')); ?></th><th class="text-end"><?php echo e(__('Actions')); ?></th></tr></thead><tbody>
        <?php $__empty_1 = true; $__currentLoopData = $roles; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $role): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <tr><td><a class="fw-semibold text-dark" href="<?php echo e(route('roles.show', $role)); ?>"><?php echo e(__($role->name)); ?></a><div class="small text-secondary"><?php echo e($role->slug); ?></div></td><td><?php echo e($role->description ? __($role->description) : '—'); ?></td><td><?php echo e($role->users_count); ?></td><td><?php echo e($role->permissions_count); ?></td><td><?php if($role->is_system): ?><span class="badge text-bg-primary"><?php echo e(__('System')); ?></span><?php else: ?><span class="badge text-bg-secondary"><?php echo e(__('Custom')); ?></span><?php endif; ?></td><td class="text-end"><div class="btn-group"><a href="<?php echo e(route('roles.show', $role)); ?>" class="btn btn-sm btn-outline-secondary" title="<?php echo e(__('View')); ?>"><i class="bi bi-eye"></i></a><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('update', $role)): ?><a href="<?php echo e(route('roles.edit', $role)); ?>" class="btn btn-sm btn-outline-secondary" title="<?php echo e(__('Edit')); ?>"><i class="bi bi-pencil"></i></a><?php endif; ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('delete', $role)): ?><form method="POST" action="<?php echo e(route('roles.destroy', $role)); ?>" onsubmit="return confirm(<?php echo \Illuminate\Support\Js::from(__('Delete this role?'))->toHtml() ?>);"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger rounded-start-0" title="<?php echo e(__('Delete')); ?>"><i class="bi bi-trash"></i></button></form><?php endif; ?></div></td></tr>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6" class="text-center py-5"><i class="bi bi-shield-lock fs-1 text-secondary"></i><div class="fw-semibold mt-3"><?php echo e(__('No roles found')); ?></div><div class="text-secondary"><?php echo e(__('Create a custom role or change the search.')); ?></div></td></tr><?php endif; ?>
    </tbody></table></div><?php if($roles->hasPages()): ?><div class="card-footer bg-white p-3"><?php echo e($roles->links()); ?></div><?php endif; ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Projects\flowmanager\resources\views/roles/index.blade.php ENDPATH**/ ?>