@php
    $selectedCategory = old('category', $ticket->category?->value ?? 'general');
    $selectedStatus = old('status', $ticket->status?->value ?? 'open');
    $selectedPriority = old('priority', $ticket->priority?->value ?? 'medium');
@endphp

@if ($errors->any())
    <div class="alert alert-danger"><div class="fw-semibold mb-2">Please correct the highlighted fields.</div><ul class="mb-0">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
@endif

<div class="row g-3">
    <div class="col-12 col-md-4"><label for="reference" class="form-label fw-semibold">Reference</label><input id="reference" name="reference" maxlength="50" class="form-control @error('reference') is-invalid @enderror" value="{{ old('reference', $ticket->reference) }}" required>@error('reference')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-8"><label for="subject" class="form-label fw-semibold">Subject</label><input id="subject" name="subject" maxlength="200" class="form-control @error('subject') is-invalid @enderror" value="{{ old('subject', $ticket->subject) }}" required>@error('subject')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-6"><label for="company_id" class="form-label fw-semibold">Company</label><select id="company_id" name="company_id" class="form-select @error('company_id') is-invalid @enderror"><option value="">No company</option>@foreach ($companies as $company)<option value="{{ $company->id }}" @selected((string) old('company_id', $ticket->company_id) === (string) $company->id)>{{ $company->name }}</option>@endforeach</select>@error('company_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-6"><label for="contact_id" class="form-label fw-semibold">Contact</label><select id="contact_id" name="contact_id" class="form-select @error('contact_id') is-invalid @enderror" data-company-contact-select data-company-source="company_id"><option value="">No contact</option>@foreach ($contacts as $contact)<option value="{{ $contact->id }}" data-company-id="{{ $contact->company_id }}" @selected((string) old('contact_id', $ticket->contact_id) === (string) $contact->id)>{{ $contact->full_name }}{{ $contact->company ? ' — '.$contact->company->name : '' }}</option>@endforeach</select>@error('contact_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-4"><label for="category" class="form-label fw-semibold">Category</label><select id="category" name="category" class="form-select @error('category') is-invalid @enderror" required>@foreach ($categories as $category)<option value="{{ $category->value }}" @selected($selectedCategory === $category->value)>{{ $category->label() }}</option>@endforeach</select>@error('category')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-6 col-md-4"><label for="status" class="form-label fw-semibold">Status</label><select id="status" name="status" class="form-select @error('status') is-invalid @enderror" required>@foreach ($statuses as $status)<option value="{{ $status->value }}" @selected($selectedStatus === $status->value)>{{ $status->label() }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-6 col-md-4"><label for="priority" class="form-label fw-semibold">Priority</label><select id="priority" name="priority" class="form-select @error('priority') is-invalid @enderror" required>@foreach ($priorities as $priority)<option value="{{ $priority->value }}" @selected($selectedPriority === $priority->value)>{{ $priority->label() }}</option>@endforeach</select>@error('priority')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label for="assigned_to" class="form-label fw-semibold">Assigned operator</label><select id="assigned_to" name="assigned_to" class="form-select @error('assigned_to') is-invalid @enderror"><option value="">Unassigned</option>@foreach ($users as $user)<option value="{{ $user->id }}" @selected((string) old('assigned_to', $ticket->assigned_to) === (string) $user->id)>{{ $user->name }} — {{ $user->email }}</option>@endforeach</select>@error('assigned_to')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label for="description" class="form-label fw-semibold">Description</label><textarea id="description" name="description" rows="6" class="form-control @error('description') is-invalid @enderror" required>{{ old('description', $ticket->description) }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label for="resolution" class="form-label fw-semibold">Resolution</label><textarea id="resolution" name="resolution" rows="4" class="form-control @error('resolution') is-invalid @enderror">{{ old('resolution', $ticket->resolution) }}</textarea><div class="form-text">Use this field when the ticket is resolved or closed.</div>@error('resolution')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div>
