@extends('layouts.app')
@section('title', __('Tickets'))
@section('page-title', __('Tickets'))
@section('page-subtitle', __('Manage support requests, ownership and resolution'))
@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"><div class="text-secondary">{{ trans_choice('ui.counts.tickets', $tickets->total(), ['count' => $tickets->total()]) }}</div>@can('create', App\Models\Ticket::class)<a href="{{ route('tickets.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i> {{ __('New ticket') }}</a>@endcan</div>
    <div class="card fm-card mb-4"><div class="card-body"><form method="GET" action="{{ route('tickets.index') }}"><div class="row g-3">
        <div class="col-12 col-lg-4"><label for="search" class="form-label fw-semibold">{{ __('Search') }}</label><input id="search" name="search" class="form-control" value="{{ $filters['search'] }}" placeholder="{{ __('Reference, subject, company, contact...') }}"></div>
        <div class="col-12 col-md-6 col-lg-2"><label for="company_id" class="form-label fw-semibold">{{ __('Company') }}</label><select id="company_id" name="company_id" class="form-select"><option value="">{{ __('All companies') }}</option>@foreach ($companies as $company)<option value="{{ $company->id }}" @selected((string) $filters['company_id'] === (string) $company->id)>{{ $company->name }}</option>@endforeach</select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="status" class="form-label fw-semibold">{{ __('Status') }}</label><select id="status" name="status" class="form-select"><option value="">{{ __('All statuses') }}</option>@foreach ($statuses as $status)<option value="{{ $status->value }}" @selected($filters['status'] === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="priority" class="form-label fw-semibold">{{ __('Priority') }}</label><select id="priority" name="priority" class="form-select"><option value="">{{ __('All priorities') }}</option>@foreach ($priorities as $priority)<option value="{{ $priority->value }}" @selected($filters['priority'] === $priority->value)>{{ $priority->label() }}</option>@endforeach</select></div>
        <div class="col-12 col-md-6 col-lg-2"><label for="assigned_to" class="form-label fw-semibold">{{ __('Assigned to') }}</label><select id="assigned_to" name="assigned_to" class="form-select"><option value="">{{ __('All users') }}</option>@foreach ($users as $user)<option value="{{ $user->id }}" @selected((string) $filters['assigned_to'] === (string) $user->id)>{{ $user->name }}</option>@endforeach</select></div>
        <div class="col-12 col-md-6 col-lg-3"><label for="sort" class="form-label fw-semibold">{{ __('Sort by') }}</label><select id="sort" name="sort" class="form-select">@foreach (['created_at' => 'Created', 'reference' => 'Reference', 'subject' => 'Subject', 'status' => 'Status', 'priority' => 'Priority', 'resolved_at' => 'Resolved'] as $value => $label)<option value="{{ $value }}" @selected($filters['sort'] === $value)>{{ __($label) }}</option>@endforeach</select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="direction" class="form-label fw-semibold">{{ __('Order') }}</label><select id="direction" name="direction" class="form-select"><option value="desc" @selected($filters['direction'] === 'desc')>{{ __('Descending') }}</option><option value="asc" @selected($filters['direction'] === 'asc')>{{ __('Ascending') }}</option></select></div>
    </div><div class="d-flex justify-content-end gap-2 mt-3"><a href="{{ route('tickets.index') }}" class="btn btn-outline-secondary">{{ __('Reset') }}</a><button class="btn btn-primary">{{ __('Apply filters') }}</button></div></form></div></div>

    <div class="card fm-card"><div class="table-responsive"><table class="table align-middle mb-0 fm-table"><thead><tr><th>{{ __('Ticket') }}</th><th>{{ __('Company / Contact') }}</th><th>{{ __('Status') }}</th><th>{{ __('Priority') }}</th><th>{{ __('Assigned to') }}</th><th>{{ __('Created') }}</th><th class="text-end">{{ __('Actions') }}</th></tr></thead><tbody>
        @forelse ($tickets as $ticket)
            @php
                $statusClass = match ($ticket->status->value) {'open' => 'text-bg-danger', 'in_progress' => 'text-bg-primary', 'waiting' => 'text-bg-warning', 'resolved' => 'text-bg-success', default => 'text-bg-secondary'};
                $priorityClass = match ($ticket->priority->value) {'urgent' => 'text-bg-danger', 'high' => 'text-bg-warning', 'low' => 'text-bg-light border text-secondary', default => 'text-bg-primary'};
            @endphp
            <tr><td><a class="fw-semibold text-dark" href="{{ route('tickets.show', $ticket) }}">{{ $ticket->subject }}</a><div class="small text-secondary">{{ $ticket->reference }} · {{ $ticket->category->label() }}</div></td><td>@if ($ticket->company)<a href="{{ route('companies.show', $ticket->company) }}">{{ $ticket->company->name }}</a>@else—@endif @if ($ticket->contact)<div class="small text-secondary"><a class="text-secondary" href="{{ route('contacts.show', $ticket->contact) }}">{{ $ticket->contact->full_name }}</a></div>@endif</td><td><span class="badge {{ $statusClass }}">{{ $ticket->status->label() }}</span></td><td><span class="badge {{ $priorityClass }}">{{ $ticket->priority->label() }}</span></td><td>{{ $ticket->assignee?->name ?: '—' }}</td><td>{{ $ticket->created_at->format('d/m/Y') }}</td><td class="text-end"><div class="btn-group"><a href="{{ route('tickets.show', $ticket) }}" class="btn btn-sm btn-outline-secondary" title="{{ __('View') }}"><i class="bi bi-eye"></i></a>@can('update', $ticket)<a href="{{ route('tickets.edit', $ticket) }}" class="btn btn-sm btn-outline-secondary" title="{{ __('Edit') }}"><i class="bi bi-pencil"></i></a>@endcan @can('delete', $ticket)<form method="POST" action="{{ route('tickets.destroy', $ticket) }}" onsubmit="return confirm(@js(__('Delete this ticket?')));">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger rounded-start-0" title="{{ __('Delete') }}"><i class="bi bi-trash"></i></button></form>@endcan</div></td></tr>
        @empty<tr><td colspan="7" class="text-center py-5"><i class="bi bi-ticket-perforated fs-1 text-secondary"></i><div class="fw-semibold mt-3">{{ __('No tickets found') }}</div><div class="text-secondary">{{ __('Open a ticket or change the active filters.') }}</div></td></tr>@endforelse
    </tbody></table></div>@if ($tickets->hasPages())<div class="card-footer bg-white p-3">{{ $tickets->links() }}</div>@endif</div>
@endsection
