@extends('layouts.app')
@section('title', __('Custom fields')) @section('page-title', __('Custom fields')) @section('page-subtitle', __('Extend FlowManager records without schema changes'))
@section('content')
<div class="row g-4"><div class="col-12 col-xl-4"><div class="card fm-card"><div class="card-body"><h5>{{ __('New custom field') }}</h5><form method="POST" action="{{ route('custom-fields.store') }}">@csrf
<div class="mb-3"><label class="form-label">{{ __('Module') }}</label><select name="resource_type" class="form-select">@foreach(['company'=>'Companies','contact'=>'Contacts','project'=>'Projects','task'=>'Tasks','asset'=>'Assets','ticket'=>'Tickets'] as $v=>$l)<option value="{{ $v }}">{{ __($l) }}</option>@endforeach</select></div>
<div class="mb-3"><label class="form-label">{{ __('Name') }}</label><input name="name" class="form-control" required></div>
<div class="mb-3"><label class="form-label">{{ __('Type') }}</label><select name="field_type" class="form-select">@foreach(['text','textarea','number','date','select','checkbox'] as $t)<option value="{{ $t }}">{{ ucfirst($t) }}</option>@endforeach</select></div>
<div class="mb-3"><label class="form-label">{{ __('Options') }}</label><textarea name="options" class="form-control" rows="4" placeholder="{{ __('One option per line for select fields') }}"></textarea></div>
<div class="form-check mb-3"><input type="checkbox" class="form-check-input" name="is_required" value="1" id="required"><label class="form-check-label" for="required">{{ __('Required') }}</label></div><button class="btn btn-primary w-100">{{ __('Create field') }}</button></form></div></div></div>
<div class="col-12 col-xl-8"><div class="card fm-card"><div class="table-responsive"><table class="table fm-table mb-0"><thead><tr><th>{{ __('Module') }}</th><th>{{ __('Field') }}</th><th>{{ __('Type') }}</th><th>{{ __('Required') }}</th><th>{{ __('Active') }}</th><th></th></tr></thead><tbody>@forelse($fields as $field)<tr><td>{{ ucfirst($field->resource_type) }}</td><td>{{ $field->name }}</td><td><span class="badge text-bg-light border">{{ $field->field_type }}</span></td><td>{{ $field->is_required ? __('Yes') : __('No') }}</td><td>{{ $field->is_active ? __('Yes') : __('No') }}</td><td class="text-end"><form method="POST" action="{{ route('custom-fields.destroy',$field) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="6" class="text-center py-5 text-secondary">{{ __('No custom fields configured.') }}</td></tr>@endforelse</tbody></table></div></div></div></div>
@endsection