@php
    $selectedStatus = old('status', $asset->status?->value ?? 'available');
@endphp

@if ($errors->any())
    <div class="alert alert-danger"><div class="fw-semibold mb-2">Please correct the highlighted fields.</div><ul class="mb-0">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
@endif

<div class="row g-3">
    <div class="col-12 col-md-4"><label for="asset_tag" class="form-label fw-semibold">Asset tag</label><input id="asset_tag" name="asset_tag" maxlength="80" class="form-control @error('asset_tag') is-invalid @enderror" value="{{ old('asset_tag', $asset->asset_tag) }}" required>@error('asset_tag')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-8"><label for="name" class="form-label fw-semibold">Asset name</label><input id="name" name="name" maxlength="180" class="form-control @error('name') is-invalid @enderror" value="{{ old('name', $asset->name) }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-4"><label for="category" class="form-label fw-semibold">Category</label><input id="category" name="category" maxlength="100" class="form-control @error('category') is-invalid @enderror" value="{{ old('category', $asset->category) }}" placeholder="Computer, Mobile, Network...">@error('category')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-4"><label for="brand" class="form-label fw-semibold">Brand</label><input id="brand" name="brand" maxlength="100" class="form-control @error('brand') is-invalid @enderror" value="{{ old('brand', $asset->brand) }}">@error('brand')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-4"><label for="model" class="form-label fw-semibold">Model</label><input id="model" name="model" maxlength="120" class="form-control @error('model') is-invalid @enderror" value="{{ old('model', $asset->model) }}">@error('model')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-6"><label for="serial_number" class="form-label fw-semibold">Serial number</label><input id="serial_number" name="serial_number" maxlength="120" class="form-control @error('serial_number') is-invalid @enderror" value="{{ old('serial_number', $asset->serial_number) }}">@error('serial_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-6"><label for="company_id" class="form-label fw-semibold">Company / owner</label><select id="company_id" name="company_id" class="form-select @error('company_id') is-invalid @enderror"><option value="">Internal / no company</option>@foreach ($companies as $company)<option value="{{ $company->id }}" @selected((string) old('company_id', $asset->company_id) === (string) $company->id)>{{ $company->name }}</option>@endforeach</select>@error('company_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-6"><label for="assigned_to" class="form-label fw-semibold">Assigned user</label><select id="assigned_to" name="assigned_to" class="form-select @error('assigned_to') is-invalid @enderror"><option value="">Unassigned</option>@foreach ($users as $user)<option value="{{ $user->id }}" @selected((string) old('assigned_to', $asset->assigned_to) === (string) $user->id)>{{ $user->name }} — {{ $user->email }}</option>@endforeach</select>@error('assigned_to')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-6"><label for="status" class="form-label fw-semibold">Status</label><select id="status" name="status" class="form-select @error('status') is-invalid @enderror" required>@foreach ($statuses as $status)<option value="{{ $status->value }}" @selected($selectedStatus === $status->value)>{{ $status->label() }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-4"><label for="purchase_date" class="form-label fw-semibold">Purchase date</label><input id="purchase_date" name="purchase_date" type="date" class="form-control @error('purchase_date') is-invalid @enderror" value="{{ old('purchase_date', $asset->purchase_date?->format('Y-m-d')) }}">@error('purchase_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 col-md-4"><label for="purchase_cost" class="form-label fw-semibold">Purchase cost</label><div class="input-group"><span class="input-group-text">€</span><input id="purchase_cost" name="purchase_cost" type="number" step="0.01" min="0" class="form-control @error('purchase_cost') is-invalid @enderror" value="{{ old('purchase_cost', $asset->purchase_cost) }}">@error('purchase_cost')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-12 col-md-4"><label for="warranty_expires_at" class="form-label fw-semibold">Warranty expires</label><input id="warranty_expires_at" name="warranty_expires_at" type="date" class="form-control @error('warranty_expires_at') is-invalid @enderror" value="{{ old('warranty_expires_at', $asset->warranty_expires_at?->format('Y-m-d')) }}">@error('warranty_expires_at')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label for="notes" class="form-label fw-semibold">Notes</label><textarea id="notes" name="notes" rows="4" class="form-control @error('notes') is-invalid @enderror">{{ old('notes', $asset->notes) }}</textarea>@error('notes')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div>
