@extends('layouts.app')
@section('title', $asset->name)
@section('page-title', $asset->name)
@section('page-subtitle'){{ $asset->asset_tag }}{{ $asset->serial_number ? ' · '.$asset->serial_number : '' }}@endsection
@section('content')
    <div class="d-flex justify-content-end flex-wrap gap-2 mb-4">@can('assign', $asset)<a href="{{ route('assets.assignment.edit', $asset) }}" class="btn btn-outline-primary"><i class="bi bi-person-check me-1"></i> {{ __('Assign asset') }}</a>@endcan @can('update', $asset)<a href="{{ route('assets.edit', $asset) }}" class="btn btn-primary"><i class="bi bi-pencil me-1"></i> {{ __('Edit asset') }}</a>@endcan</div>
    <div class="row g-4"><div class="col-12 col-xl-8"><div class="card fm-card"><div class="card-header fm-card-header"><div><h2 class="fm-card-title">{{ __('Asset details') }}</h2><p class="fm-card-subtitle">{{ __('Inventory and lifecycle information') }}</p></div></div><div class="card-body"><div class="row g-4">
        <div class="col-6 col-md-4"><div class="small text-secondary">{{ __('Status') }}</div><div class="fw-semibold">{{ $asset->status->label() }}</div></div><div class="col-6 col-md-4"><div class="small text-secondary">{{ __('Category') }}</div><div class="fw-semibold">{{ $asset->category ?: '—' }}</div></div><div class="col-12 col-md-4"><div class="small text-secondary">{{ __('Assigned to') }}</div><div class="fw-semibold">{{ $asset->assignee?->name ?: __('Unassigned') }}</div></div>
        <div class="col-12 col-md-4"><div class="small text-secondary">{{ __('Brand') }}</div><div class="fw-semibold">{{ $asset->brand ?: '—' }}</div></div><div class="col-12 col-md-4"><div class="small text-secondary">{{ __('Model') }}</div><div class="fw-semibold">{{ $asset->model ?: '—' }}</div></div><div class="col-12 col-md-4"><div class="small text-secondary">{{ __('Serial number') }}</div><div class="fw-semibold">{{ $asset->serial_number ?: '—' }}</div></div>
        <div class="col-12 col-md-4"><div class="small text-secondary">{{ __('Company') }}</div>@if ($asset->company)<a class="fw-semibold" href="{{ route('companies.show', $asset->company) }}">{{ $asset->company->name }}</a>@else<div class="fw-semibold">{{ __('Internal') }}</div>@endif</div><div class="col-12 col-md-4"><div class="small text-secondary">{{ __('Purchase date') }}</div><div class="fw-semibold">{{ $asset->purchase_date?->format('d/m/Y') ?: '—' }}</div></div><div class="col-12 col-md-4"><div class="small text-secondary">{{ __('Purchase cost') }}</div><div class="fw-semibold">{{ $asset->purchase_cost !== null ? '€ '.number_format((float) $asset->purchase_cost, 2, ',', '.') : '—' }}</div></div>
        <div class="col-12 col-md-4"><div class="small text-secondary">{{ __('Warranty expires') }}</div><div class="fw-semibold">{{ $asset->warranty_expires_at?->format('d/m/Y') ?: '—' }}</div></div>
        <div class="col-12"><div class="small text-secondary mb-1">{{ __('Notes') }}</div><div>{{ $asset->notes ?: '—' }}</div></div>
    </div></div></div></div>
    <div class="col-12 col-xl-4"><div class="card fm-card"><div class="card-body"><h2 class="fm-card-title mb-3">{{ __('Record information') }}</h2><div class="d-flex justify-content-between py-2 border-bottom"><span class="text-secondary">{{ __('Created by') }}</span><strong>{{ $asset->creator?->name ?: __('System') }}</strong></div><div class="d-flex justify-content-between py-2 border-bottom"><span class="text-secondary">{{ __('Created') }}</span><strong>{{ $asset->created_at->format('d/m/Y H:i') }}</strong></div><div class="d-flex justify-content-between pt-2"><span class="text-secondary">{{ __('Updated') }}</span><strong>{{ $asset->updated_at->format('d/m/Y H:i') }}</strong></div></div></div></div></div>
@endsection
