@extends('layouts.app')
@section('title', 'Tasks')
@section('page-title', 'Tasks')
@section('page-subtitle', 'Track project work, ownership, priority and deadlines')
@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"><div class="text-secondary">{{ $tasks->total() }} task{{ $tasks->total() === 1 ? '' : 's' }}</div>@can('create', App\Models\Task::class)<a href="{{ route('tasks.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i> New task</a>@endcan</div>
    <div class="card fm-card mb-4"><div class="card-body"><form method="GET" action="{{ route('tasks.index') }}"><div class="row g-3">
        <div class="col-12 col-lg-4"><label for="search" class="form-label fw-semibold">Search</label><input id="search" name="search" class="form-control" value="{{ $filters['search'] }}" placeholder="Task or project..."></div>
        <div class="col-12 col-md-6 col-lg-2"><label for="project_id" class="form-label fw-semibold">Project</label><select id="project_id" name="project_id" class="form-select"><option value="">All projects</option>@foreach ($projects as $project)<option value="{{ $project->id }}" @selected((string) $filters['project_id'] === (string) $project->id)>{{ $project->code }} — {{ $project->name }}</option>@endforeach</select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="status" class="form-label fw-semibold">Status</label><select id="status" name="status" class="form-select"><option value="">All statuses</option>@foreach ($statuses as $status)<option value="{{ $status->value }}" @selected($filters['status'] === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="priority" class="form-label fw-semibold">Priority</label><select id="priority" name="priority" class="form-select"><option value="">All priorities</option>@foreach ($priorities as $priority)<option value="{{ $priority->value }}" @selected($filters['priority'] === $priority->value)>{{ $priority->label() }}</option>@endforeach</select></div>
        <div class="col-12 col-md-6 col-lg-2"><label for="assigned_to" class="form-label fw-semibold">Assignee</label><select id="assigned_to" name="assigned_to" class="form-select"><option value="">All users</option>@foreach ($users as $user)<option value="{{ $user->id }}" @selected((string) $filters['assigned_to'] === (string) $user->id)>{{ $user->name }}</option>@endforeach</select></div>
        <div class="col-12 col-md-6 col-lg-3"><label for="sort" class="form-label fw-semibold">Sort by</label><select id="sort" name="sort" class="form-select">@foreach (['due_date' => 'Due date', 'title' => 'Title', 'status' => 'Status', 'priority' => 'Priority', 'created_at' => 'Created'] as $value => $label)<option value="{{ $value }}" @selected($filters['sort'] === $value)>{{ $label }}</option>@endforeach</select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="direction" class="form-label fw-semibold">Order</label><select id="direction" name="direction" class="form-select"><option value="asc" @selected($filters['direction'] === 'asc')>Ascending</option><option value="desc" @selected($filters['direction'] === 'desc')>Descending</option></select></div>
    </div><div class="d-flex justify-content-end gap-2 mt-3"><a href="{{ route('tasks.index') }}" class="btn btn-outline-secondary">Reset</a><button class="btn btn-primary" type="submit">Apply filters</button></div></form></div></div>

    <div class="card fm-card"><div class="table-responsive"><table class="table align-middle mb-0 fm-table"><thead><tr><th>Task</th><th>Project</th><th>Status</th><th>Priority</th><th>Assignee</th><th>Due date</th><th class="text-end">Actions</th></tr></thead><tbody>
        @forelse ($tasks as $task)
            @php
                $statusClass = match ($task->status->value) {'completed' => 'text-bg-success', 'in_progress' => 'text-bg-primary', 'blocked' => 'text-bg-danger', 'cancelled' => 'text-bg-secondary', default => 'text-bg-light border text-secondary'};
                $priorityClass = match ($task->priority->value) {'urgent' => 'text-bg-danger', 'high' => 'text-bg-warning', 'low' => 'text-bg-light border text-secondary', default => 'text-bg-primary'};
            @endphp
            <tr><td><a class="fw-semibold text-dark" href="{{ route('tasks.show', $task) }}">{{ $task->title }}</a></td><td><a href="{{ route('projects.show', $task->project) }}">{{ $task->project->code }}</a><div class="small text-secondary">{{ $task->project->name }}</div></td><td><span class="badge {{ $statusClass }}">{{ $task->status->label() }}</span></td><td><span class="badge {{ $priorityClass }}">{{ $task->priority->label() }}</span></td><td>{{ $task->assignee?->name ?: '—' }}</td><td>{{ $task->due_date?->format('d/m/Y') ?: '—' }}</td><td class="text-end"><div class="btn-group"><a href="{{ route('tasks.show', $task) }}" class="btn btn-sm btn-outline-secondary" title="View"><i class="bi bi-eye"></i></a>@can('update', $task)<a href="{{ route('tasks.edit', $task) }}" class="btn btn-sm btn-outline-secondary" title="Edit"><i class="bi bi-pencil"></i></a>@endcan @can('delete', $task)<form method="POST" action="{{ route('tasks.destroy', $task) }}" onsubmit="return confirm('Delete this task?');">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger rounded-start-0" title="Delete"><i class="bi bi-trash"></i></button></form>@endcan</div></td></tr>
        @empty<tr><td colspan="7" class="text-center py-5"><i class="bi bi-check2-square fs-1 text-secondary"></i><div class="fw-semibold mt-3">No tasks found</div><div class="text-secondary">Create a task or change the active filters.</div></td></tr>@endforelse
    </tbody></table></div>@if ($tasks->hasPages())<div class="card-footer bg-white p-3">{{ $tasks->links() }}</div>@endif</div>
@endsection
