@extends('layouts.app')
@section('title', __('Tasks'))
@section('page-title', __('Tasks'))
@section('page-subtitle', __('Track project work, ownership, priority and deadlines'))
@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"><div class="text-secondary">{{ trans_choice('ui.counts.tasks', $tasks->total(), ['count' => $tasks->total()]) }}</div>@can('create', App\Models\Task::class)<a href="{{ route('tasks.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i> {{ __('New task') }}</a>@endcan</div>
    <div class="card fm-card mb-4"><div class="card-body"><form method="GET" action="{{ route('tasks.index') }}"><div class="row g-3">
        <div class="col-12 col-lg-4"><label for="search" class="form-label fw-semibold">{{ __('Search') }}</label><input id="search" name="search" class="form-control" value="{{ $filters['search'] }}" placeholder="{{ __('Task or project...') }}"></div>
        <div class="col-12 col-md-6 col-lg-2"><label for="project_id" class="form-label fw-semibold">{{ __('Project') }}</label><select id="project_id" name="project_id" class="form-select"><option value="">{{ __('All projects') }}</option>@foreach ($projects as $project)<option value="{{ $project->id }}" @selected((string) $filters['project_id'] === (string) $project->id)>{{ $project->code }} — {{ $project->name }}</option>@endforeach</select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="status" class="form-label fw-semibold">{{ __('Status') }}</label><select id="status" name="status" class="form-select"><option value="">{{ __('All statuses') }}</option>@foreach ($statuses as $status)<option value="{{ $status->value }}" @selected($filters['status'] === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="priority" class="form-label fw-semibold">{{ __('Priority') }}</label><select id="priority" name="priority" class="form-select"><option value="">{{ __('All priorities') }}</option>@foreach ($priorities as $priority)<option value="{{ $priority->value }}" @selected($filters['priority'] === $priority->value)>{{ $priority->label() }}</option>@endforeach</select></div>
        <div class="col-12 col-md-6 col-lg-2"><label for="assigned_to" class="form-label fw-semibold">{{ __('Assignee') }}</label><select id="assigned_to" name="assigned_to" class="form-select"><option value="">{{ __('All users') }}</option>@foreach ($users as $user)<option value="{{ $user->id }}" @selected((string) $filters['assigned_to'] === (string) $user->id)>{{ $user->name }}</option>@endforeach</select></div>
        <div class="col-12 col-md-6 col-lg-3"><label for="sort" class="form-label fw-semibold">{{ __('Sort by') }}</label><select id="sort" name="sort" class="form-select">@foreach (['due_date' => 'Due date', 'title' => 'Title', 'status' => 'Status', 'priority' => 'Priority', 'created_at' => 'Created'] as $value => $label)<option value="{{ $value }}" @selected($filters['sort'] === $value)>{{ __($label) }}</option>@endforeach</select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="direction" class="form-label fw-semibold">{{ __('Order') }}</label><select id="direction" name="direction" class="form-select"><option value="asc" @selected($filters['direction'] === 'asc')>{{ __('Ascending') }}</option><option value="desc" @selected($filters['direction'] === 'desc')>{{ __('Descending') }}</option></select></div>
    </div><div class="d-flex justify-content-end gap-2 mt-3"><a href="{{ route('tasks.index') }}" class="btn btn-outline-secondary">{{ __('Reset') }}</a><button class="btn btn-primary" type="submit">{{ __('Apply filters') }}</button></div></form></div></div>


    @include('partials.saved-filters', ['filterResource' => 'tasks', 'filterRoute' => 'tasks.index'])
    <div class="d-flex justify-content-end mb-3">@include('partials.per-page', ['resourceName' => 'tasks'])</div>
    <div data-bulk-container>
        @include('partials.bulk-toolbar', ['bulkResource' => 'tasks', 'statuses' => $statuses, 'priorities' => $priorities, 'users' => $users])

    <div class="card fm-card"><div class="table-responsive"><table class="table align-middle mb-0 fm-table" data-table-resource="tasks"><thead><tr><th style="width:42px"><input type="checkbox" class="form-check-input" data-bulk-select-all aria-label="{{ __('Select all') }}"></th><th>{{ __('Task') }}</th><th data-column="project">{{ __('Project') }}</th><th data-column="status">{{ __('Status') }}</th><th data-column="priority">{{ __('Priority') }}</th><th data-column="assignee">{{ __('Assignee') }}</th><th data-column="due_date">{{ __('Due date') }}</th><th class="text-end">{{ __('Actions') }}</th></tr></thead><tbody>
        @forelse ($tasks as $task)
            @php
                $statusClass = match ($task->status->value) {'completed' => 'text-bg-success', 'in_progress' => 'text-bg-primary', 'blocked' => 'text-bg-danger', 'cancelled' => 'text-bg-secondary', default => 'text-bg-light border text-secondary'};
                $priorityClass = match ($task->priority->value) {'urgent' => 'text-bg-danger', 'high' => 'text-bg-warning', 'low' => 'text-bg-light border text-secondary', default => 'text-bg-primary'};
            @endphp
            <tr><td><input type="checkbox" class="form-check-input" value="{{ $task->id }}" data-bulk-checkbox aria-label="{{ __('Select') }}"></td><td><a class="fw-semibold text-dark" href="{{ route('tasks.show', $task) }}">{{ $task->title }}</a></td><td data-column="project"><a href="{{ route('projects.show', $task->project) }}">{{ $task->project->code }}</a><div class="small text-secondary">{{ $task->project->name }}</div></td><td data-column="status"><span class="badge {{ $statusClass }}">{{ $task->status->label() }}</span></td><td data-column="priority"><span class="badge {{ $priorityClass }}">{{ $task->priority->label() }}</span></td><td data-column="assignee">{{ $task->assignee?->name ?: '—' }}</td><td data-column="due_date">{{ $task->due_date?->format('d/m/Y') ?: '—' }}</td><td class="text-end"><div class="btn-group"><a href="{{ route('tasks.show', $task) }}" class="btn btn-sm btn-outline-secondary" title="{{ __('View') }}"><i class="bi bi-eye"></i></a>@can('update', $task)<a href="{{ route('tasks.edit', $task) }}" class="btn btn-sm btn-outline-secondary" title="{{ __('Edit') }}"><i class="bi bi-pencil"></i></a>@endcan @can('delete', $task)<form method="POST" action="{{ route('tasks.destroy', $task) }}" onsubmit="return confirm(@js(__('Delete this task?')));">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger rounded-start-0" title="{{ __('Delete') }}"><i class="bi bi-trash"></i></button></form>@endcan</div></td></tr>
        @empty<tr><td colspan="8" class="text-center py-5"><i class="bi bi-check2-square fs-1 text-secondary"></i><div class="fw-semibold mt-3">{{ __('No tasks found') }}</div><div class="text-secondary">{{ __('Create a task or change the active filters.') }}</div></td></tr>@endforelse
    </tbody></table></div>@if ($tasks->hasPages())<div class="card-footer bg-white p-3">{{ $tasks->links() }}</div>@endif</div>
    </div>
@endsection
