@extends('layouts.app')
@section('title', 'Roles')
@section('page-title', 'Roles')
@section('page-subtitle', 'Control permission sets and application access profiles')
@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"><div class="text-secondary">{{ $roles->total() }} role{{ $roles->total() === 1 ? '' : 's' }}</div>@can('create', App\Models\Role::class)<a href="{{ route('roles.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i> New role</a>@endcan</div>
    <div class="card fm-card mb-4"><div class="card-body"><form method="GET" action="{{ route('roles.index') }}"><div class="row g-3 align-items-end"><div class="col-12 col-lg-10"><label for="search" class="form-label fw-semibold">Search</label><input id="search" name="search" class="form-control" value="{{ $search }}" placeholder="Name, slug or description..."></div><div class="col-12 col-lg-2"><div class="d-flex gap-2"><a href="{{ route('roles.index') }}" class="btn btn-outline-secondary flex-fill">Reset</a><button class="btn btn-primary flex-fill">Search</button></div></div></div></form></div></div>
    <div class="card fm-card"><div class="table-responsive"><table class="table align-middle mb-0 fm-table"><thead><tr><th>Role</th><th>Description</th><th>Users</th><th>Permissions</th><th>Type</th><th class="text-end">Actions</th></tr></thead><tbody>
        @forelse ($roles as $role)
            <tr><td><a class="fw-semibold text-dark" href="{{ route('roles.show', $role) }}">{{ $role->name }}</a><div class="small text-secondary">{{ $role->slug }}</div></td><td>{{ $role->description ?: '—' }}</td><td>{{ $role->users_count }}</td><td>{{ $role->permissions_count }}</td><td>@if ($role->is_system)<span class="badge text-bg-primary">System</span>@else<span class="badge text-bg-secondary">Custom</span>@endif</td><td class="text-end"><div class="btn-group"><a href="{{ route('roles.show', $role) }}" class="btn btn-sm btn-outline-secondary" title="View"><i class="bi bi-eye"></i></a>@can('update', $role)<a href="{{ route('roles.edit', $role) }}" class="btn btn-sm btn-outline-secondary" title="Edit"><i class="bi bi-pencil"></i></a>@endcan @can('delete', $role)<form method="POST" action="{{ route('roles.destroy', $role) }}" onsubmit="return confirm('Delete this role?');">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger rounded-start-0" title="Delete"><i class="bi bi-trash"></i></button></form>@endcan</div></td></tr>
        @empty<tr><td colspan="6" class="text-center py-5"><i class="bi bi-shield-lock fs-1 text-secondary"></i><div class="fw-semibold mt-3">No roles found</div><div class="text-secondary">Create a custom role or change the search.</div></td></tr>@endforelse
    </tbody></table></div>@if ($roles->hasPages())<div class="card-footer bg-white p-3">{{ $roles->links() }}</div>@endif</div>
@endsection
