@extends('layouts.app')
@section('title', $role->name)
@section('page-title', $role->name)
@section('page-subtitle'){{ $role->slug }} · {{ $role->is_system ? 'System role' : 'Custom role' }}@endsection
@section('content')
    <div class="d-flex justify-content-end gap-2 mb-4">@can('update', $role)<a href="{{ route('roles.edit', $role) }}" class="btn btn-primary"><i class="bi bi-pencil me-1"></i> Edit role</a>@endcan</div>
    <div class="row g-4"><div class="col-12 col-xl-8"><div class="card fm-card mb-4"><div class="card-header fm-card-header"><div><h2 class="fm-card-title">Permissions</h2><p class="fm-card-subtitle">Capabilities granted by this role</p></div></div><div class="card-body"><div class="d-flex flex-wrap gap-2">@forelse ($role->permissions->sortBy('slug') as $permission)<span class="badge text-bg-light border text-secondary">{{ $permission->slug }}</span>@empty<span class="text-secondary">No permissions assigned.</span>@endforelse</div></div></div>
        <div class="card fm-card"><div class="card-header fm-card-header"><div><h2 class="fm-card-title">Users</h2><p class="fm-card-subtitle">Accounts assigned to this role</p></div></div><div class="list-group list-group-flush">@forelse ($role->users as $user)<a href="{{ route('users.show', $user) }}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"><span><span class="fw-semibold d-block">{{ $user->name }}</span><span class="small text-secondary">{{ $user->email }}</span></span><i class="bi bi-chevron-right"></i></a>@empty<div class="p-4 text-secondary text-center">No users assigned to this role.</div>@endforelse</div></div>
    </div><div class="col-12 col-xl-4"><div class="card fm-card"><div class="card-body"><h2 class="fm-card-title mb-3">Role information</h2><p class="text-secondary">{{ $role->description ?: 'No description.' }}</p><div class="d-flex justify-content-between py-2 border-bottom"><span class="text-secondary">Type</span><strong>{{ $role->is_system ? 'System' : 'Custom' }}</strong></div><div class="d-flex justify-content-between py-2 border-bottom"><span class="text-secondary">Users</span><strong>{{ $role->users->count() }}</strong></div><div class="d-flex justify-content-between pt-2"><span class="text-secondary">Permissions</span><strong>{{ $role->permissions->count() }}</strong></div></div></div></div></div>
@endsection
